### ISSUE TITLE
Table names with underscores and/or singular seem to break the generator

### ISSUE THREAD

**Issue by Sir4ur0n** [digitallyinduced/ihp#262]
Hi, this is my very first time playing with IHP, I hope I have not overlooked something, please bear with me :bow: 

# Singular, underscore

Steps to reproduce:
* `ihp-new foobar`
* `cd foobar`
* `./start`
* Create a table named `foo_bar`, no need to add columns besides the default UUID
* Right click "Generate controller"
* Click on "Generate" on top right
* :boom: 
> Web/Controller/Foo_bars.hs: openFile: does not exist (No such file or directory)
An exception was raised while running the action CreateControllerAction

```shell
$ tree Web 
Web
├── Controller
│   ├── FooBars.hs
│   └── Prelude.hs
├── FrontController.hs
├── Routes.hs
├── Types.hs
└── View
    ├── Context.hs
    ├── Foo_bar
    │   └── Index.hs
    ├── Layout.hs
    └── Prelude.hs

3 directories, 9 files
```

I highly suspect things go south because of the underscore + the suffixed `s`:
* In `Web/Controller` the name of the module is `FooBars` (camelcase, plural suffix `s`)
* In `Web/View` the parent folder (module) is named `Foo_bar` (snake case, singular)

# Singular, no underscore

Running exactly the same steps but naming the table `foobar` (no underscore, singular) succeeds during code generation, but breaks when trying to go to the app:
```
Error while compiling

Web/Controller/Foobars.hs:4:1: error:
    Could not find module ‘Web.View.Foobars.Index’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
4 | import Web.View.Foobars.Index
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:5:1: error:
    Could not find module ‘Web.View.Foobars.New’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Web.View.Foobars.New
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:6:1: error:
    Could not find module ‘Web.View.Foobars.Edit’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Web.View.Foobars.Edit
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:7:1: error:
    Could not find module ‘Web.View.Foobars.Show’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import Web.View.Foobars.Show
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:4:1: error:
    Could not find module ‘Web.View.Foobars.Index’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
4 | import Web.View.Foobars.Index
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:5:1: error:
    Could not find module ‘Web.View.Foobars.New’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Web.View.Foobars.New
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:6:1: error:
    Could not find module ‘Web.View.Foobars.Edit’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Web.View.Foobars.Edit
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:7:1: error:
    Could not find module ‘Web.View.Foobars.Show’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import Web.View.Foobars.Show
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:4:1: error:
    Could not find module ‘Web.View.Foobars.Index’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
4 | import Web.View.Foobars.Index
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:5:1: error:
    Could not find module ‘Web.View.Foobars.New’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Web.View.Foobars.New
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:6:1: error:
    Could not find module ‘Web.View.Foobars.Edit’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Web.View.Foobars.Edit
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:7:1: error:
    Could not find module ‘Web.View.Foobars.Show’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import Web.View.Foobars.Show
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:4:1: error:
    Could not find module ‘Web.View.Foobars.Index’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
4 | import Web.View.Foobars.Index
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:5:1: error:
    Could not find module ‘Web.View.Foobars.New’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Web.View.Foobars.New
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:6:1: error:
    Could not find module ‘Web.View.Foobars.Edit’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Web.View.Foobars.Edit
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:7:1: error:
    Could not find module ‘Web.View.Foobars.Show’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import Web.View.Foobars.Show
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:4:1: error:
    Could not find module ‘Web.View.Foobars.Index’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
4 | import Web.View.Foobars.Index
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:5:1: error:
    Could not find module ‘Web.View.Foobars.New’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
5 | import Web.View.Foobars.New
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:6:1: error:
    Could not find module ‘Web.View.Foobars.Edit’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
6 | import Web.View.Foobars.Edit
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Web/Controller/Foobars.hs:7:1: error:
    Could not find module ‘Web.View.Foobars.Show’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
7 | import Web.View.Foobars.Show
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

```shell
$ tree Web 
Web
├── Controller
│   ├── Foobars.hs
│   └── Prelude.hs
├── FrontController.hs
├── Routes.hs
├── Types.hs
└── View
    ├── Context.hs
    ├── Foobar
    │   ├── Edit.hs
    │   ├── Index.hs
    │   ├── New.hs
    │   └── Show.hs
    ├── Layout.hs
    └── Prelude.hs

3 directories, 12 files
```

# Plural, no underscore

Running exactly the same steps but naming the table `foobars` (no underscore, plural) succeeds during code generation and running the app.

```shell
$ tree Web 
Web
├── Controller
│   ├── Foobars.hs
│   └── Prelude.hs
├── FrontController.hs
├── Routes.hs
├── Types.hs
└── View
    ├── Context.hs
    ├── Foobars
    │   ├── Edit.hs
    │   ├── Index.hs
    │   ├── New.hs
    │   └── Show.hs
    ├── Layout.hs
    └── Prelude.hs

3 directories, 12 files
```

# Plural, underscore

> Web/Controller/Foo_bars.hs: openFile: does not exist (No such file or directory)
An exception was raised while running the action CreateControllerAction

```shell
$ tree Web
Web
├── Controller
│   ├── FooBars.hs
│   └── Prelude.hs
├── FrontController.hs
├── Routes.hs
├── Types.hs
└── View
    ├── Context.hs
    ├── Foo_bars
    │   └── Index.hs
    ├── Layout.hs
    └── Prelude.hs

3 directories, 9 files
```

In case this is relevant: I am on NixOS 20.03

**Comment by mpscholten** [comment]
Hey, thanks for reporting :) We've recently updated the code generators, so this might be broken since we did those changes. Will take a look asap

**Comment by mpscholten** [comment]
Should be fixed via https://github.com/digitallyinduced/ihp/pull/263 👍 

After the PR is merged you can update to the specific commit of the fix by changing line 4 in your projects `default.nix`. Then rebuild everything using `nix-shell -j auto --cores 0 --run 'make -B .envrc'`. After that you can use the project as usual by using `./start`.

**Comment by Sir4ur0n** [comment]
Thank you @mpscholten , I confirm this now works for underscores, however it still doesn't work for singular.

I can't reopen this issue, would you like me to open a new one?

E.g. if my table name is `barfoo`, I still get many errors:
```
Web/View/Barfoo/Show.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html ShowView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/New.hs:7:32: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html NewView { .. } = [hsx|
  |                                ^...

Web/View/Barfoo/Index.hs:7:34: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html IndexView { .. } = [hsx|
  |                                  ^...

Web/View/Barfoo/Edit.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html EditView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/Show.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html ShowView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/New.hs:7:32: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html NewView { .. } = [hsx|
  |                                ^...

Web/View/Barfoo/Index.hs:7:34: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html IndexView { .. } = [hsx|
  |                                  ^...

Web/View/Barfoo/Edit.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html EditView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/Show.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html ShowView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/New.hs:7:32: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html NewView { .. } = [hsx|
  |                                ^...

Web/View/Barfoo/Index.hs:7:34: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html IndexView { .. } = [hsx|
  |                                  ^...

Web/View/Barfoo/Edit.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html EditView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/Show.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html ShowView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/New.hs:7:32: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html NewView { .. } = [hsx|
  |                                ^...

Web/View/Barfoo/Index.hs:7:34: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html IndexView { .. } = [hsx|
  |                                  ^...

Web/View/Barfoo/Edit.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html EditView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/Show.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html ShowView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/New.hs:7:32: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html NewView { .. } = [hsx|
  |                                ^...

Web/View/Barfoo/Index.hs:7:34: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html IndexView { .. } = [hsx|
  |                                  ^...

Web/View/Barfoo/Edit.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html EditView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/Show.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html ShowView { .. } = [hsx|
  |                                 ^...

Web/View/Barfoo/New.hs:7:32: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html NewView { .. } = [hsx|
  |                                ^...

Web/View/Barfoo/Index.hs:7:34: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html IndexView { .. } = [hsx|
  |                                  ^...

Web/View/Barfoo/Edit.hs:7:33: error:
    • Data constructor not in scope: BarfoosAction
    • Perhaps you meant ‘BarfooAction’ (imported from Web.View.Prelude)
  |
7 |     html EditView { .. } = [hsx|
  |                                 ^...
```

**Comment by mpscholten** [comment]
Just reopened it. I guess we should write some tests for the code generators :D Will take a look

**Comment by mpscholten** [comment]
@Sir4ur0n this has been now fixed by @Laobiz :) We also added some tests to make sure this won't break in the future.

**Comment by Sir4ur0n** [comment]
Awesome, thank you everyone!
